Add buildServer docker functions

diff --git a/zsh/conf_molikuners-MacBook-Pro b/zsh/conf_molikuners-MacBook-Pro
--- a/zsh/conf_molikuners-MacBook-Pro
+++ b/zsh/conf_molikuners-MacBook-Pro
@@ -4,6 +4,50 @@ export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PR
 
 export GPG_TTY=$(tty)
 
+inDir() {
+  local pwdPath
+  pwdPath=$(pwd)
+  [ "${pwdPath:0:${#1}}" = $1 ]
+}
+
+dockerExsists() {
+  [ "docker ps -aq -f name=$1" ]
+}
+
+dockerCreateBuildServer() {
+  if dockerExsists build-server; then
+    echo "Can't create an exsisting server again!" >&2
+    return 1
+  fi
+  docker create -it --name build-server --hostname build-server -v ~/.gradle/caches:/root/.gradle/caches -v ~/IdeaProjects:/root/IdeaProjects -v ~/workspace:/root/workspace --entrypoint 'echo "Please detatch and exec your stuff" && while true; do sleep 9999999; done' javiersantos/android-ci
+}
+
+dockerRunning() {
+  eval "$(docker inspect -f '{{.State.Running}}' $1 2>/dev/null || echo 'false')"
+}
+
+buildServer() {
+  if ! inDir ~/workspace && ! inDir ~/IdeaProjects; then
+    echo "You need to be in one of the mounted dirs to be able to build" >&2
+    return 1
+  fi
+  local pathPart
+  pathPart="$(pwd | cut -d '/' -f '4-')"
+  if dockerRunning build-server; then
+    if ! [ ! "$*" ]; then
+      docker exec -it -w /root/$pathPart build-server "$@"
+    else
+      docker exec -it -w /root/$pathPart build-server bash
+    fi
+  elif dockerExsists build-server; then
+    docker start build-server
+    buildServer $@ # execute itself and start bash session
+  else
+    dockerCreateBuildServer
+    buildServer $@
+  fi
+}
+
 gitMolikuner() {
   if ! git status &>/dev/null; then
     echo "You need to have an exsisting git repo" >&2
